addons:
  apt:
    packages:
      - docker-ce

sudo: required
language: python

services:
  - docker

install:
  - pip install tox

env:
  - TOX_ENV: ansible25
  - TOX_ENV: ansible26
  - TOX_ENV: ansible27

script:
  - tox --workdir $(mktemp -d) -e ${TOX_ENV}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
