addons:
  apt:
    packages:
      - docker-ce

sudo: required
language: python
python: 3.6

services:
  - docker

install:
  - pip install tox

env:
  - TOX_ENV: ansible28
  - TOX_ENV: ansible29

script:
  - tox --workdir $(mktemp -d) -e ${TOX_ENV}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
